# configs/model/anomaly_transformer.yaml
# Anomaly Transformer Configuration
_target_: src.models.anomaly_transformer.AnomalyTransformer   # your class
model:
  type: anomaly_transformer
  size: medium
  d_model: 512
  n_heads: 8
  n_layers: 6
  dropout: 0.1
  max_seq_len: 200
