# configs/model/motion_transformer.yaml
_target_: src.models.motion_transformer.MotionTransformer
model:
  type: motion_transformer
  size: medium
  d_model: 256
  n_queries: 6
  encoder_layers: 4
  decoder_layers: 6
  n_heads: 8
  prediction_horizon: 30
