# AIS data processing configuration
_target_: src.data.datamodule.AISDataModule

name: ais_processed

# Data paths
data_path: ${data_dir}/ais_data.parquet
processed_path: ${data_dir}/processed/
maritime_network_path: ${data_dir}/maritime_network.pkl

# Data processing parameters
preprocessing:
  # Filtering parameters
  max_speed: 50.0  # knots
  min_speed: 0.1   # knots
  stationary_threshold: 600  # seconds
  max_gap: 1800  # seconds (30 minutes)
  min_points: 6
  
  # Trajectory segmentation
  max_voyage_duration: 72  # hours
  segment_length: 20  # max points per segment
  
  # Resampling
  resample_interval: 600  # seconds (10 minutes)
  
  # Spatial filtering
  bounding_box:
    lat_min: 54.5
    lat_max: 58.0
    lon_min: 9.5
    lon_max: 13.0

# Data splits
train_ratio: 0.7
val_ratio: 0.15
test_ratio: 0.15
split_method: "temporal"  # temporal, random, vessel

# Data loading
batch_size: 128
num_workers: 8
pin_memory: true
persistent_workers: true
prefetch_factor: 2

# Sequence parameters
seq_len: 20
pred_horizon: 10
overlap: 0.5  # Overlap between sequences

# Weather data integration
weather:
  enabled: true
  weather_path: ${data_dir}/weather_data.nc
  interpolation_method: "linear"
  features: ["wind_speed", "wind_direction", "wave_height", "visibility"]

# Graph processing
graph_processing:
  enabled: true
  cache_graphs: true
  graph_cache_path: ${data_dir}/graph_cache/
  local_radius: 10.0  # km

# Memory optimization
chunk_size: 10000
use_dask: true
memory_limit: "8GB"