# Base experimental configuration
defaults:
  - _self_
  - data: ais_processed
  - model: traisformer
  - trainer: gpu
  - callbacks: default
  - logger: wandb

# Experiment metadata
experiment_name: ${model.name}_base_experiment
description: "Base experiment configuration for maritime trajectory prediction"
tags: ["baseline", "${model.name}"]

# Seeds for reproducibility
seed: 42
deterministic: false

# Early stopping
early_stopping:
  monitor: "val_f1"
  patience: 10
  mode: "max"
  min_delta: 0.001

# Model checkpointing
checkpointing:
  monitor: "val_f1"
  mode: "max"
  save_top_k: 3
  save_last: true
  filename: "{epoch:02d}-{val_f1:.3f}"