# Comprehensive hyperparameter search space
defaults:
  - experiment/base
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    study_name: maritime_architecture_sweep
    n_trials: 200
    n_jobs: 1
    
    # Optuna sampler configuration
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 42
      n_startup_trials: 20
      n_ei_candidates: 24
    
    # Search space parameters
    params:
      # Model architecture selection
      model: choice(traisformer, ais_fuser, lstm, xgboost)
      
      # Shared parameters across models
      data.batch_size: choice(64, 128, 256)
      trainer.max_epochs: choice(50, 100, 150)
      
      # TrAISformer specific parameters
      "+model/traisformer":
        model.d_model: choice(256, 512, 768)
        model.nhead: choice(4, 8, 12)
        model.num_layers: choice(4, 6, 8)
        model.dim_feedforward: choice(1024, 2048, 4096)
        model.dropout: interval(0.1, 0.5)
        model.optimizer.lr: interval(1e-5, 1e-2)
        model.multi_res_beta: interval(0.1, 0.5)
        
      # AISFuser specific parameters
      "+model/ais_fuser":
        model.d_model: choice(256, 512, 768)
        model.graph.polyline_dim: choice(128, 256, 512)
        model.ssl.beta: interval(0.1, 0.5)
        model.ssl.temperature: interval(0.05, 0.1)
        model.optimizer.lr: interval(1e-5, 1e-2)
        
      # LSTM specific parameters
      "+model/lstm":
        model.hidden_size: choice(128, 256, 512)
        model.num_layers: choice(2, 3, 4)
        model.dropout: interval(0.1, 0.4)
        model.optimizer.lr: interval(1e-4, 1e-2)
        
      # XGBoost specific parameters (SSA optimization)
      "+model/xgboost":
        model.n_estimators: interval(50, 200)
        model.max_depth: interval(3, 15)
        model.learning_rate: interval(0.01, 0.3)
        model.subsample: interval(0.6, 1.0)
        model.colsample_bytree: interval(0.6, 1.0)

# Additional sweep configuration
sweep:
  method: "bayes"  # bayes, grid, random
  metric:
    name: "val_f1"
    goal: "maximize"
  early_terminate:
    type: "hyperband"
    min_iter: 10