# Configuration for AISFuser model
defaults:
  - _self_

_target_: src.models.ais_fuser.AISFuserLightning

graph:
  polyline_dim: 256
  cluster_eps: 0.015
transformer:
  d_model: 512
  nhead: 8
  num_layers: 6
ssl_beta: 0.3
weather_dim: 64
num_classes: 9
optimizer:
  lr: 0.0001
  weight_decay: 0.01
