# LSTM model configuration
_target_: src.models.baselines.LSTMModel
name: lstm

# Model architecture
input_size: 4  # lat, lon, sog, cog
hidden_size: 128
num_layers: 2
output_size: 4  # lat, lon, sog, cog
dropout: 0.2

# Optimizer parameters
learning_rate: 0.001
weight_decay: 0.0001
