# XGBoost model configuration
_target_: src.models.baselines.XGBoostModel
name: xgboost

# Model parameters
max_depth: 6
learning_rate: 0.1
n_estimators: 100

# Feature processing
flatten_sequence: true
seq_len: 10
feature_dim: 4
