hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    study_name: ${experiment_name}_optuna  # inherits from your top-level config
    direction: minimize
    n_trials: 20
    n_jobs: 1
    max_failure_rate: 0.0

    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # (Optional) Uncomment to use a persistent storage backend:
    # storage: sqlite:///optuna.db
