# @package _global_
defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    study_name: null
    storage: null
    n_trials: 20
    n_jobs: 1
    max_failure_rate: 0.0
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: null
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true
