# GPU trainer configuration

# Hardware settings
accelerator: gpu
devices: 1
precision: 16-mixed

# Training parameters
max_epochs: 100
learning_rate: 1e-4
weight_decay: 0.01
optimizer: adam
scheduler: null

# Validation and logging
check_val_every_n_epoch: 1
val_check_interval: null
log_every_n_steps: 50

# Performance optimization
gradient_clip_val: 1.0
benchmark: true
compile: false
deterministic: false

# Early stopping and checkpointing handled by callbacks
