# Global configuration for maritime trajectory prediction
defaults:
  - _self_
  - mode: train  # Default mode
  - data: ais_processed
  - model: traisformer
  - trainer: gpu
  - callbacks: default
  - logger: wandb
  - experiment: base

# Global parameters
seed: 42
data_dir: ${oc.env:MARITIME_DATA_DIR,data}
output_dir: ${oc.env:MARITIME_OUTPUT_DIR,outputs}
name: ${model.name}_experiment
wandb_project: maritime_trajectory_prediction
