# SOTA Model Training Configuration Examples

# Anomaly Transformer Configuration
anomaly_transformer:
  model:
    type: "anomaly_transformer"
    size: "medium"  # small, medium, large
    custom_params:
      d_model: 512
      n_heads: 8
      n_layers: 6
      dropout: 0.1
      max_seq_len: 200

  training:
    batch_size: 32
    learning_rate: 1e-4
    weight_decay: 1e-5
    max_epochs: 100
    patience: 15
    gradient_clip: 1.0
    validation_freq: 1

  data:
    sequence_length: 50
    prediction_horizon: 10  # Not used for anomaly detection
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    num_workers: 4
    pin_memory: true

  logging:
    use_wandb: true
    project_name: "maritime-anomaly-detection"
    experiment_name: "anomaly_transformer_v1"
    log_freq: 10
    save_freq: 5

  paths:
    data_dir: "./data/processed"
    output_dir: "./outputs/anomaly_transformer"
    checkpoint_dir: "./checkpoints/anomaly_transformer"
    log_dir: "./logs/anomaly_transformer"

---

# Motion Transformer Configuration
motion_transformer:
  model:
    type: "motion_transformer"
    size: "medium"  # small, medium, large
    custom_params:
      d_model: 256
      n_queries: 6
      encoder_layers: 4
      decoder_layers: 6
      n_heads: 8
      prediction_horizon: 30

  training:
    batch_size: 16  # Smaller batch size due to larger model
    learning_rate: 1e-4
    weight_decay: 1e-5
    max_epochs: 150
    patience: 20
    gradient_clip: 1.0
    loss_type: "best_of_n"  # or "weighted"
    validation_freq: 1

  data:
    sequence_length: 30
    prediction_horizon: 30
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    num_workers: 4
    pin_memory: true

  logging:
    use_wandb: true
    project_name: "maritime-trajectory-prediction"
    experiment_name: "motion_transformer_v1"
    log_freq: 10
    save_freq: 5

  paths:
    data_dir: "./data/processed"
    output_dir: "./outputs/motion_transformer"
    checkpoint_dir: "./checkpoints/motion_transformer"
    log_dir: "./logs/motion_transformer"

---

# Baseline Model Configuration
baseline_trajectory:
  model:
    type: "baseline"
    task: "trajectory_prediction"
    custom_params:
      input_dim: 4
      hidden_dim: 128
      num_layers: 2
      output_dim: 4
      dropout: 0.2
      bidirectional: true

  training:
    batch_size: 64
    learning_rate: 1e-3
    weight_decay: 1e-4
    max_epochs: 50
    patience: 10
    gradient_clip: 1.0
    validation_freq: 1

  data:
    sequence_length: 20
    prediction_horizon: 10
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    num_workers: 4
    pin_memory: true

  logging:
    use_wandb: false
    project_name: "maritime-baselines"
    experiment_name: "lstm_baseline_v1"
    log_freq: 20
    save_freq: 10

  paths:
    data_dir: "./data/processed"
    output_dir: "./outputs/baseline_trajectory"
    checkpoint_dir: "./checkpoints/baseline_trajectory"
    log_dir: "./logs/baseline_trajectory"

---

# Baseline Anomaly Detection Configuration
baseline_anomaly:
  model:
    type: "baseline"
    task: "anomaly_detection"
    custom_params:
      input_dim: 4
      encoding_dim: 64
      hidden_dims: [128, 96]
      activation: "relu"
      dropout: 0.2

  training:
    batch_size: 64
    learning_rate: 1e-3
    weight_decay: 1e-4
    max_epochs: 50
    patience: 10
    gradient_clip: 1.0
    validation_freq: 1

  data:
    sequence_length: 30
    prediction_horizon: 10  # Not used for anomaly detection
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    num_workers: 4
    pin_memory: true

  logging:
    use_wandb: false
    project_name: "maritime-baselines"
    experiment_name: "autoencoder_baseline_v1"
    log_freq: 20
    save_freq: 10

  paths:
    data_dir: "./data/processed"
    output_dir: "./outputs/baseline_anomaly"
    checkpoint_dir: "./checkpoints/baseline_anomaly"
    log_dir: "./logs/baseline_anomaly"

---

# Small Scale Testing Configuration
test_config:
  model:
    type: "motion_transformer"
    size: "small"

  training:
    batch_size: 8
    learning_rate: 1e-3
    weight_decay: 1e-5
    max_epochs: 5
    patience: 3
    gradient_clip: 1.0
    validation_freq: 1

  data:
    sequence_length: 15
    prediction_horizon: 10
    train_split: 0.8
    val_split: 0.1
    test_split: 0.1
    num_workers: 2
    pin_memory: false

  logging:
    use_wandb: false
    project_name: "maritime-test"
    experiment_name: "quick_test"
    log_freq: 1
    save_freq: 1

  paths:
    data_dir: "./data/test"
    output_dir: "./outputs/test"
    checkpoint_dir: "./checkpoints/test"
    log_dir: "./logs/test"
