# Weights & Biases logger configuration

type: wandb
name: ${name}
save_dir: ${output_dir}/logs
version: null

# Wandb specific settings
wandb_project: ${wandb_project}
wandb_tags:
  - ${model.type}
  - ${mode}
offline: false
log_model: true
