# @package _global_
# Configuration for prediction mode

mode: predict

# Prediction specific settings
predict:
  input_file: null  # Required: path to input data
  output_file: null  # Optional: path to save predictions
  format: csv  # Output format: csv, json, npz
  num_samples: 10  # Number of trajectory samples
  num_steps: 12  # Prediction horizon
  threshold: 0.5  # Anomaly detection threshold
  visualize: false  # Create visualization plots
  batch_inference: false  # Process multiple inputs
  real_time: false  # Real-time processing mode
