# @package _global_
# Configuration for evaluation mode

mode: evaluate

# Evaluation specific settings
evaluation:
  data_path: null  # Path to evaluation data, null for synthetic
  output_dir: ${output_dir}/evaluation
  metrics:
    - trajectory_prediction
    - anomaly_detection
    - computational_performance
  save_predictions: true
  save_visualizations: true
  generate_report: true
  batch_size: 32
  num_samples: 50  # For trajectory sampling
  confidence_threshold: 0.5  # For anomaly detection
